services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: parola123
      POSTGRES_DB: CryptoExchangeDB
    ports:
      - "5432:5432"
    volumes:
      - ./.local-docker-run:/var/lib/postgresql/data
