spring:
  application:
    name: crypto-trading-platform
  datasource:
    url: jdbc:postgresql://localhost:5432/CryptoExchangeDB
    username: admin
    password: parola123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always